/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablesRouteRouteImport } from './routes/tables/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TablesIndexRouteImport } from './routes/tables/index'
import { Route as ChartsIndexRouteImport } from './routes/charts/index'

const TablesRouteRoute = TablesRouteRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesIndexRoute = TablesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TablesRouteRoute,
} as any)
const ChartsIndexRoute = ChartsIndexRouteImport.update({
  id: '/charts/',
  path: '/charts/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tables': typeof TablesRouteRouteWithChildren
  '/charts': typeof ChartsIndexRoute
  '/tables/': typeof TablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts': typeof ChartsIndexRoute
  '/tables': typeof TablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tables': typeof TablesRouteRouteWithChildren
  '/charts/': typeof ChartsIndexRoute
  '/tables/': typeof TablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tables' | '/charts' | '/tables/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/charts' | '/tables'
  id: '__root__' | '/' | '/tables' | '/charts/' | '/tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TablesRouteRoute: typeof TablesRouteRouteWithChildren
  ChartsIndexRoute: typeof ChartsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/': {
      id: '/tables/'
      path: '/'
      fullPath: '/tables/'
      preLoaderRoute: typeof TablesIndexRouteImport
      parentRoute: typeof TablesRouteRoute
    }
    '/charts/': {
      id: '/charts/'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TablesRouteRouteChildren {
  TablesIndexRoute: typeof TablesIndexRoute
}

const TablesRouteRouteChildren: TablesRouteRouteChildren = {
  TablesIndexRoute: TablesIndexRoute,
}

const TablesRouteRouteWithChildren = TablesRouteRoute._addFileChildren(
  TablesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TablesRouteRoute: TablesRouteRouteWithChildren,
  ChartsIndexRoute: ChartsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
